services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Spinbits\SyliusGoogleAnalytics4Plugin\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Kernel.php'

    Spinbits\SyliusGoogleAnalytics4Plugin\Factory\RenderHeadTwigFactoryInterface:
        class: Spinbits\SyliusGoogleAnalytics4Plugin\Factory\RenderHeadTwigFactory
        arguments:
            $enabled: '%spinbits_sylius_google_analytics4.enabled%'
            $additionalParams: '%spinbits_sylius_google_analytics4.additionalParameters%'
            $templateName: '%spinbits_sylius_google_analytics4.templateName%'
            
    Spinbits\SyliusGoogleAnalytics4Plugin\Provider\GoogleTagIdProviderInterface:
        class: Spinbits\SyliusGoogleAnalytics4Plugin\Provider\GoogleTagIdProvider
        arguments:
            $defaultId: '%spinbits_sylius_google_analytics4.id%'
            $channelsIds: '%spinbits_sylius_google_analytics4.channels_ids%'
            
    Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            
    Spinbits\SyliusGoogleAnalytics4Plugin\Factory\ItemFactoryInterface:
        class: Spinbits\SyliusGoogleAnalytics4Plugin\Factory\ItemFactory
        arguments:
            $productVariantResolver: '@sylius.product_variant_resolver.default'
            
    Spinbits\SyliusGoogleAnalytics4Plugin\Factory\ItemFactoryFromProductVariantInterface:
        class: Spinbits\SyliusGoogleAnalytics4Plugin\Factory\ItemFactoryFromProductVariant    
    
    Spinbits\SyliusGoogleAnalytics4Plugin\Factory\EventsBagSessionFactory:
        decorates: session.factory
        arguments: ['@.inner']
